export const majors = [
  "Ingeniería y Ciencias Ambientales",
  "Computación y Sistemas de Información",
  "Ingeniería de Construcción",
  "Ingeniería Eléctrica",
  "Ingeniería Estructural",
  "Ingeniería Geotécnica",
  "Ingeniería Hidráulica",
  "Ingeniería Mecánica",
  "Ingeniería Minera",
  "Ingeniería Química",
  "Ingeniería en Investigación Operativa",
  "Ingeniería de Sistemas de Transportes",
  "Ingeniería de Software",
  "Geociencias",
  "Ingeniería Biológica",
  "Ingeniería Biomédica",
  "Ingeniería Matemática",
  "Ingeniería y Arquitectura",
  "Ingeniería, Diseño e Innovación",
  "Ingeniería Robótica",
  "Ingeniería Física",
  "Ingeniería Civil",
];
